name: Compile Supported Portable Distributions
on:
  workflow_dispatch:
    inputs:
      release:
        description: Upload to a tagged release?
        required: true
        type: boolean
      dwpose:
        description: Build DWPose?
        required: true
        type: boolean
jobs:
  compile-all:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            api: cuda
          - os: windows-latest
            api: cuda
          - os: macos-13
            api: mps
    uses: ./.github/workflows/compile.yml
    with:
      os: ${{ matrix.os }}
      api: ${{ matrix.api }}
      release: ${{ inputs.release }}
      dwpose: ${{ inputs.dwpose }}
